import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FlowbiteContext from "@/components/FlowbiteContext";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  SignOutButton,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  // title: "Create Next App",
  title: "MongoNotes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <SignedOut>
            <div className="flex items-center justify-center w-full h-[90vh]">
              <div className="border rounded-lg p-4 border-white text-white">
                <SignInButton />
              </div>
            </div>
          </SignedOut>
          <SignedIn>
            <FlowbiteContext>{children}</FlowbiteContext>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
